---
title: Estimating error rates for bullet comparisons in forensic science
author:
  - name: Yawei Ge
    email: yaweige@iastate.edu
    affiliation: Iowa State University
    footnote: Corresponding Author
  - name: Heike Hofmann
    email: hofmann@iastate.edu
    affiliation: Iowa State University
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "An awesome journal"
date: "`r Sys.Date()`"
bibliography: references.bib
#linenumbers: true
#numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
header-includes:
  -  \usepackage{hyperref}
  -  \usepackage{graphicx}
  -  \usepackage[dvipsnames]{xcolor}
---

\newcommand{\hh}[1]{{\textcolor{orange}{#1}}}
\newcommand{\yg}[1]{{\textcolor{blue}{#1}}}

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_



Introduction and literature review
====================================

The firearm examiners are focusing on the same source and different source problems of bullets and cartridge cases which serve as important forensic evidence in the court/to the jurors. The subjectivity in the traditional forensic process is called to be reduced or complemented by more objective methods [@Council2009; @PCAST2016]. Some automatic matching algorithms are developed which usually return a similarity score (0-1) to quantify the similarity or the probability to be an actual match for a certain comparison. However, this raises questions about how to interpret the reported probabilities and how these probabilities are distributed. Thus, it is not all clear how to conduct inferences based on the similarity scores. [The paper] proposed binomial and beta-binomial for the number of matched cells of the CMC method. Thus, it provides a way to quantify the theoretical error rate of the algorithm. However, for the bullets LEA comparison, we haven’t established similar distributional results. In this paper, we will evaluate the possible models/distributions for the LEA comparisons scores generated by the random forest proposed by @Hare2016. And then, we will also evaluate the error rates based on the estimated distribution for the automatic matching algorithm.

In section 2, we will discuss proper distributional forms of the RF scores. In section 3, we will introduce the LAPD data set and the estimated distributions. In section 4, the theoretical error rates based on the distributions are discussed. In section 5, we evaluate the performance of the estimation, stability of the distribution within a changing sample size context. In section 6, we will conclude the discussion.

The distributional forms of the similarity scores
============================

The quantitative methods used to objectively measure the similarity between LEAs reports various quantities, such as counts, correlations, distances, probabilities and more generally similarity scores [references]. To understand how those quantities reflect the strength of evidence and to study the underlying the error rates in making decisions based on those quantities, distributional forms are usually set up [references]. Particularly, we are focusing on the similarity scores which range from 0 to 1 and the probabilities reported as the likelihood of an actual match. The similarity scores reported in the forensic researches are usually categorized into two categories.  One is that the compared LEAs or other forensic evidences are actual matches, the other is that the compared LEAs or other forensic evidences are not matches. We name the former as known matches (KM) and the latter as known non-matches (KNM), and the corresponding distributions are named as KM distributions and KNM distributions [figures]. However, this kind of classifications can be investigated only in the lab environment where the ground truth is known. When we make any decisions based on any quantitative measurement, we are actually making a distinguish between those two potential distributions. The strength of any identification process is also measured by the disparities of those distributions. However, in practice, we can hardly discriminate those two distributions totally, thus, we are never 100% sure which distribution the observed score comes from. This is where the identification error raises. 

For the purpose of illustration, we have a look at the examples (could use Hamby and other sets, not necessarily LAPD) [figure(histogram?)]. Those are RF scores generated from the automatic matching algorithm [references]. The scores from the RF can be explained as probabilities that calculated through the algorithm based on the trained model to quantify the likelihood that a pair of LEAs are actual a match. Or we can think of the RF scores as general similarity scores that quantify the similarities. As the name indicated, the higher RF scores imply higher chances to be a match. For different combination of ammunition and firearms, the scores are distributed differently. It is expected that systematic differences exist there for different cases. So, it is necessary to study the scores under controlled conditions, thus, a threshold for the scores to do classifications varies based on the changes of the underlying distributions.

We can see from the figure [figure], which is a typical one we usually have for the scores, that the distributions are apart for the majorities. In the bullet LEA comparison problems, we usually have a well separated bullet scores but for the land scores, there are usually some overlaps [Susan]. We propose beta distributions for those scores. Because the beta distribution is a well-used one in statistics to describe a quantity from 0 to 1 which is usually a probability for another distribution in Bayesian analysis. And it is very flexible to capture any unimodal shape from 0 to 1. However, it may not be adequate to explain a heavy tail or even a second mode. Thus, we consider the beta mixture distribution which is a more complex distribution than the beta distribution which is a special case of the beta mixture distribution. In the beta mixture distribution, we introduce a hierarchical structure with a prior probability to combine two beta distributions as one. The distributions are defined below.

The reported random forest scores are denoted as $Y_{ij}$ for $j^{th}$ LEA comparison within class $i$, where $i = 1$ is KM and $i = 2$ is KNM. $Y_{ij}$'s are considered independent and identically distributed within each class, i.e.

\begin{align*}
Y_{1j} \stackrel{iid}{\sim}  Betamix(p_1, \mu_{11}, \phi_{11}, \mu_{12}, \phi_{12})\\
Y_{2j} \stackrel{iid}{\sim}  Betamix(p_2, \mu_{21}, \phi_{21}, \mu_{22}, \phi_{22})
\end{align*}

where $\mu_{ik}$ and $\phi_{ik}$ are distribution parameters for $i^{th}$ class and $k^{th}$ component, $k = 1$ or $2$. And $p_i$ is the prior probability for the first component in $i^{th}$ class, thus, $1-p_i$ is the prior probability for the second component in $i^{th}$ class. Note that we are using the mean and precision parameterization of beta distributions which simplifies the math in calculation. It's equivalent to the usual $\alpha$ and $\beta$ parameterization through the following transformation:

\begin{align*}
\mu = \frac{\alpha}{\alpha+\beta} \\
\phi = \alpha + \beta
\end{align*}

LAPD data set and the estimated distributions
==========================================

For the following sections of the paper, we will base our analysis on the LAPD data sets. This is a large data set of … It is the first time such a large data set available to the researcher, which makes it possible for a statistical analysis for the distribution of the RF scores. (More! And number of land comparisons for different cases)

The estimation was done using EM algorithm implemented in “betareg” package in R [reference]. This is a numeric method for calculating maximum likelihood estimators (MLE) when direct computation is not available or hard. Instead of a simpler beta model, we start with the more complex beta mixture model, see how well it fits the data and test if some components are necessary. We estimate two-component beta mixture distribution for both KNM and KM distributions as follows:

(table: report alpha, beta, mean, variance)

(figure: the estimated curve with observations drawn as rugs or boxplots in the bottom)

The estimated distributions are also shown in the figure [figure] with rugs in the bottom shown as the actual observations. As expected, the estimated distributions show the properties we desire for the similarity scores. The majorities of the estimated distributions are apart from each other, while the minority part between the two distributions has some overlap. It’s worth to note that (how the actual observations are distributed compared with the curves). The distributions usually have longer tails than points where the observations show up but with small probabilities. And the shapes of the distributions are ideal and potentially flexible enough to capture the empirical distributional information of the observations.

It’s also helpful to see how the individual components look like in the beta mixture distributions [figure]. The KNM and KM distributions seem to share a common component while keep the other components far apart from each other. The separated components represent the ideal cases where the bullet land engraved areas preserved the information of source well and result clear distinct separation. The shared components represent the cases where the KM results lower scores because of some degree of tank rash, pitting, breakoff or other damages on the bullets and the KNM results higher score because of the random identification effect. These properties together well explained the observed empirical distribution of similarity scores in our cases. Particularly, the heavier tail of the KM comparisons is explicitly included the form of the model by one of the components.

We need to do formal statistical tests to verify some of the points mentioned before. We would like to know if simpler beta distributions are sufficient to model the data. We would also quantify the variability of estimations of the distribution through parametric bootstrap.

(test, bootstrap inference, and report the model for the full data)

Evaluate the error rates
================================

(report theoretical error rates)

Estimations with changing sample size
================================

(quantify the variation, reproduce some results in the previous sections with changing sample size)

Conclusion
==================================




The following content is help information of the Elsevier template (keep for reference for a while)
================================

The Elsevier article class
==========================

#### Installation

If the document class *elsarticle* is not available on your computer,
you can download and install the system package *texlive-publishers*
(Linux) or install the LaTeX package *elsarticle* using the package
manager of your TeX installation, which is typically TeX Live or MikTeX.

#### Usage

Once the package is properly installed, you can use the document class
*elsarticle* to create a manuscript. Please make sure that your
manuscript follows the guidelines in the Guide for Authors of the
relevant journal. It is not necessary to typeset your manuscript in
exactly the same way as an article, unless you are submitting to a
camera-ready copy (CRC) journal.

#### Functionality

The Elsevier article class is based on the standard article class and
supports almost all of the functionality of that class. In addition, it
features commands and options to format the

-   document style

-   baselineskip

-   front matter

-   keywords and MSC codes

-   theorems, definitions and proofs

-   lables of enumerations

-   citation style and labeling.

Front matter
============

The author names and affiliations could be formatted in two ways:

(1) Group the authors per affiliation.

(2) Use footnotes to indicate the affiliations.

See the front matter of this document for examples. You are recommended
to conform your choice to the journal you are submitting to.

Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.


References {#references .unnumbered}
==========
